name: lighthouse_provider
description: Lighthouse provider, provides VR lighthouses the "easy" way.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  meta: ^1.7.0
  mutex: ^3.0.0
  rxdart: ^0.27.3
  tuple: ^2.0.0
  collection: ^1.15.0
  convert: ^3.0.1
  lighthouse_back_end:
    path: ../lighthouse_back_end
  shared_platform:
    path: ../../shared/shared_platform
  lighthouse_logger:
    path: ../lighthouse_logger

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_providers:
    path: ../lighthouse_providers
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
