name: flutter_web_bluetooth_back_end
description: A lighthouse back end to use flutter web bluetooth.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter_web_bluetooth: ^0.0.6+2
  mutex: ^3.0.0
  rxdart: ^0.27.3
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_logger:
    path: ../../lighthouse_logger

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
