name: bluez_back_end
description: A lighthouse back end to use BlueZ.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  bluez: ^0.7.4
  mutex: ^3.0.0
  rxdart: ^0.27.3
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
