name: bluez_back_end
description: A lighthouse back end to use BlueZ.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  bluez: ^0.8.0
  mutex: ^3.0.0
  rxdart: ^0.27.5
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_logger:
    path: ../../lighthouse_logger

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
