name: bluez_back_end
description: A lighthouse back end to use BlueZ.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  bluez: ^0.8.2
  mutex: ^3.1.0
  rxdart: ^0.28.0
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_logger:
    path: ../../lighthouse_logger

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
