name: fake_back_end
description: A lighthouse back end to use fake data.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_web_bluetooth: ^0.1.0
  meta: ">=1.3.0 <2.0.0"
  mutex: ^3.0.0
  rxdart: ^0.27.5
  convert: ^3.1.1
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_providers:
    path: ../../lighthouse_providers
  shared_platform:
    path: ../../../shared/shared_platform
  lighthouse_logger:
    path: ../../lighthouse_logger

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
  lighthouse_test_helper:
    path: ../../lighthouse_test_helper
