name: fake_back_end
description: A lighthouse back end to use fake data.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter_web_bluetooth: ^0.0.6+2
  mutex: ^3.0.0
  rxdart: ^0.27.3
  convert: ^3.0.1
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_providers:
    path: ../../lighthouse_providers
  shared_platform:
    path: ../../../shared/shared_platform

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
