name: lighthouse_providers
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter_web_bluetooth: ^0.2.3
  meta: ">=1.3.0 <2.0.0"
  rxdart: ^0.27.7
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_back_end:
    path: ../lighthouse_back_end
  shared_platform:
    path: ../../shared/shared_platform
  lighthouse_logger:
    path: ../lighthouse_logger

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
