name: lighthouse_providers
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter_web_bluetooth: ^0.0.6+2
  meta: ^1.7.0
  rxdart: ^0.27.3
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_back_end:
    path: ../lighthouse_back_end
  shared_platform:
    path: ../../shared/shared_platform

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
