name: shared_platform
description: A library that helps with making platform specific code paths available for web and io builds.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
