name: lighthouse_back_end
description: An interface for a specific lighthouse back end.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  meta: ">=1.3.0 <2.0.0"
  convert: ^3.1.1
  collection: ^1.16.0
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_logger:
    path: ../lighthouse_logger

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  shared_platform:
    path: ../../shared/shared_platform
  lighthouse_providers:
    path: ../lighthouse_providers
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
