name: lighthouse_test_helper
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  meta: ">=1.3.0 <2.0.0"
  rxdart: ^0.27.7
  shared_platform:
    path: ../../shared/shared_platform
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_back_end:
    path: ../lighthouse_back_end
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_providers:
    path: ../lighthouse_providers
  test: ^1.24.3

dev_dependencies:
  lints: ^3.0.0
