name: lighthouse_logger
description: A logger for the lighthouse packages
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  logging: ^1.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.5
