name: lighthouse_logger
description: A logger for the lighthouse packages
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
