name: lighthouse_logger
description: A logger for the lighthouse packages
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3