name: Flutter_Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.9.2'

      - name: Restore packages
        run: flutter pub get

      - name: Generate code
        run: flutter packages pub run build_runner build

      - name: Analyze
        run: flutter analyze

      - name: Formatted
        run: flutter format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
